### ISSUE TITLE
Mostrar en el mapa descripción del material necesaria de los espacios a reservar(Clientes)

### ISSUE THREAD

**Issue by JotaGalera** [JotaGalera/TFG_Javier_Galera_Garrido#37]
El usuario debe poder ver el inventario disponible para el alquiler de cada espacio. Para ello solo tendrá que visitar la sección del mapa y pinchar encima de una habitación, deberá poder ver la descripción de esta y el material disponible.
Si el material es actualizado, el mapa debe de mostrar el material actual disponible.

**Comment by JJ** [comment]
Una vez más, un issue debe ser una historia de usuario. ¿Quién quiere ver qué? ¿Qué entradas? ¿Qué salidas? ¿Cómo sabemos que esto está hecho?

**Comment by JJ** [comment]
Tampoco has usado milestones con este issue, y lo has cerrado con un solo commit. Debería haber milestones que mostraran las diferentes etapas de desarrollo, y una metodología de desarrollo sistemática.
